jsonlist/config/routes.rb
Rails.application.routes.draw do

  root 'contacts#index'
  get 'contacts/new' => 'contacts#new', as: :new_contact
  post "contacts" => 'contacts#create', as: :contacts
  get "contacts/:id" => 'contacts#show', as: :contact

  namespace :api do
    get "contacts" => 'contacts#index'
  end
end

jsonlist/app/models/contact.rb
class Contact < ActiveRecord::Base

  attachment :profile

  validates :first_name, :last_name, :email, :profile, presence: true
  
  def full_name
    [last_name, first_name].join(", ")
  end
end

jsonlist/app/controllers/api/contacts_controller.rb
class Api::ContactsController < ApplicationController

  before_action do
    request.format = :json
  end

  def index
    @contacts = Contact.all
  end
end

jsonlist/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all


    view = ApplicationController.view_context_class.new("#{Rails.root}/app/views")
    @contacts_json = JbuilderTemplate.new(view).encode do |json|
      json.contacts @contacts do |contact|
        json.id contact.id
        json.first_name contact.first_name
        json.last_name contact.last_name
        json.full_name contact.full_name
        json.url contact_path(id: contact.id)
        json.thumbnail_url Refile.attachment_url(contact, :profile, :fill, 100, 100, format: 'png')
        json.profile_url Refile.attachment_url(contact, :profile, :fill, 500, 500, format: 'png')
      end

    end

  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new params.require(:contact).permit(:first_name, :last_name, :email, :profile)
    if @contact.save
      redirect_to contact_path(id: @contact.id)
    else
      render :new
    end
  end

  def show
    @contact = Contact.find params[:id]
  end
end

jsonlist/app/helpers/api/contacts_helper.rb
module Api::ContactsHelper
end

jsonlist/app/helpers/contacts_helper.rb
module ContactsHelper
end

jsonlist/app/views/contacts/index.html.erb
<h1>Contacts#index</h1>
<p>Find me in app/views/contacts/index.html.erb</p>

<%= link_to "New Contact", new_contact_path %>


<%= react_component 'ContactList', @contacts_json, {prerender: true} %>

jsonlist/app/views/contacts/new.html.erb
<h1>Contacts#new</h1>

<% if @contact.errors.any? %>
  <div class="errors">
    <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @contact do |f| %>
  <div>
    <%= f.label :first_name %><br/>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %><br/>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %><br/>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :profile, "Profile Image" %><br/>
    <%= f.attachment_field :profile %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

jsonlist/app/views/contacts/show.html.erb
<h1>Contacts#show</h1>
<p>Find me in app/views/contacts/show.html.erb</p>

jsonlist/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jsonlist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>