slack_review/config/routes.rb
Rails.application.routes.draw do
  get 'signin' => 'sessions#new', as: :sign_in
  post "signin" => 'sessions#create'

  root 'rooms#index'

  get 'rooms/:id' => 'rooms#show', as: :room

  namespace :api do
    get 'rooms/:id' => 'rooms#show'
    post "rooms/:id/messages" => 'messages#create'
  end

end

slack_review/app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :room
  belongs_to :user
end

slack_review/app/models/room.rb
class Room < ActiveRecord::Base
  has_many :messages
  # unsure if I'll use, but it exists
  #has_many :users, through: :messages
end

slack_review/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :messages
  # unsure if we'll use the rooms I've posted to
  #has_many :rooms, through: :messages
end

slack_review/app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController

  before_action :authenticate_user!

  def create
    @message = Message.new params.require(:message).permit(:body)
    # set room
    @message.room = Room.find params[:id]
    # set user
    # @message.user = User.all.sample
    # if we had auth working
    @message.user = @current_user
    if @message.save
      render status: 201, json: @message
    else
      render status: 422, json: @message.errors
    end
  end
end

slack_review/app/controllers/api/rooms_controller.rb
class Api::RoomsController < ApplicationController

  before_action :authenticate_user!

  def show
    @room = Room.find params[:id]
  end
end

slack_review/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action do
    @current_user = User.find_by id: session[:user_id]
  end

  def authenticate_user!
    if @current_user.blank?
      redirect_to sign_in_path
    end
  end
end

slack_review/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :authenticate_user!
  
  def index
    @rooms = Room.all
  end

  def show
    @rooms = Room.all
    @room = Room.find params[:id]
  end
end

slack_review/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    username = params[:username]
    password = params[:password]

    user = User.find_by username: username
    if user.present? && user.authenticate(password)
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end

  end
end

slack_review/app/helpers/api/messages_helper.rb
module Api::MessagesHelper
end

slack_review/app/helpers/api/rooms_helper.rb
module Api::RoomsHelper
end

slack_review/app/helpers/application_helper.rb
module ApplicationHelper
end

slack_review/app/helpers/rooms_helper.rb
module RoomsHelper
end

slack_review/app/helpers/sessions_helper.rb
module SessionsHelper
end

slack_review/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SlackReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="app">
  <%= yield %>
</div>

</body>
</html>

slack_review/app/views/rooms/index.html.erb
<div class="rooms">
  <ul>
    <% @rooms.each do |room| %>
      <li><%= link_to room.name, room_path(id: room.id) %>
    <% end %>
  </ul>
</div>

slack_review/app/views/rooms/show.html.erb
  <div class="rooms">
    <ul>
      <% @rooms.each do |room| %>
        <li><%= link_to room.name, room_path(id: room.id) %>
      <% end %>
    </ul>
  </div>

  <%= react_component 'Room', {room: @room} %>